// <auto-generated />
using System;
using LineNex.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LineNex.Infrastructure.Migrations
{
    [DbContext(typeof(SqlContext))]
    partial class SqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LineNex.Domain.Entity.ApplicationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("ApplicationToken");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.DistributionPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DistributionPoint");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.DistributionPointMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DistributionPointId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DistributionPointId");

                    b.HasIndex("MachineId");

                    b.ToTable("DistributionPointMachine");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.DistributionPointStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DistributionPointId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistributionPointId");

                    b.ToTable("DistributionPointStock");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.InventoryDistributionPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DistributionPointId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DistributionPointId");

                    b.HasIndex("InventoryId");

                    b.ToTable("InventoryDistributionPoint");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.Layout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Layout");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Machine");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.MachineConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("MachineConnection");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.MachineSensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("SensorId");

                    b.ToTable("MachineSensor");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.MachineSensorData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MachineSensorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MachineSensorMachineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MachineSensorSensorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MachineSensorId");

                    b.ToTable("MachineSensorData");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.MachineTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("TagId");

                    b.ToTable("MachineTag");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permission");

                    b.HasData(
                        new
                        {
                            Id = new Guid("17ec40e3-9be7-4201-b2a6-13fb71d41e94"),
                            Code = "RDR",
                            CreatedAt = new DateTime(2025, 1, 1, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            CreatedById = new Guid("d17e004b-2335-4850-8a8a-4597cf73f862"),
                            IsDeleted = false,
                            Name = "Reader"
                        },
                        new
                        {
                            Id = new Guid("27ec40e3-9be7-4201-b2a6-13fb71d41e94"),
                            Code = "CRT",
                            CreatedAt = new DateTime(2025, 1, 1, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            CreatedById = new Guid("d17e004b-2335-4850-8a8a-4597cf73f862"),
                            IsDeleted = false,
                            Name = "Create"
                        },
                        new
                        {
                            Id = new Guid("37ec40e3-9be7-4201-b2a6-13fb71d41e94"),
                            Code = "UPD",
                            CreatedAt = new DateTime(2025, 1, 1, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            CreatedById = new Guid("d17e004b-2335-4850-8a8a-4597cf73f862"),
                            IsDeleted = false,
                            Name = "Update"
                        },
                        new
                        {
                            Id = new Guid("47ec40e3-9be7-4201-b2a6-13fb71d41e94"),
                            Code = "DEL",
                            CreatedAt = new DateTime(2025, 1, 1, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            CreatedById = new Guid("d17e004b-2335-4850-8a8a-4597cf73f862"),
                            IsDeleted = false,
                            Name = "Delete"
                        });
                });

            modelBuilder.Entity("LineNex.Domain.Entity.ProductionLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("ProductionLine");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.ProductionLineMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductionLineId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("ProductionLineId");

                    b.ToTable("ProductionLineMachine");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b7ec40e3-9be7-4201-b2a6-13fb71d41e94"),
                            Code = "ADMIN",
                            CreatedAt = new DateTime(2025, 1, 1, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            CreatedById = new Guid("d17e004b-2335-4850-8a8a-4597cf73f862"),
                            IsDeleted = false,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = new Guid("a7ec40e3-9be7-4201-b2a6-13fb71d41e94"),
                            Code = "USER",
                            CreatedAt = new DateTime(2025, 1, 1, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            CreatedById = new Guid("d17e004b-2335-4850-8a8a-4597cf73f862"),
                            IsDeleted = false,
                            Name = "Standard User"
                        });
                });

            modelBuilder.Entity("LineNex.Domain.Entity.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermission");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 1, 1, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            CreatedById = new Guid("d17e004b-2335-4850-8a8a-4597cf73f862"),
                            IsDeleted = false,
                            PermissionId = new Guid("17ec40e3-9be7-4201-b2a6-13fb71d41e94"),
                            RoleId = new Guid("b7ec40e3-9be7-4201-b2a6-13fb71d41e94")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 1, 1, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            CreatedById = new Guid("d17e004b-2335-4850-8a8a-4597cf73f862"),
                            IsDeleted = false,
                            PermissionId = new Guid("27ec40e3-9be7-4201-b2a6-13fb71d41e94"),
                            RoleId = new Guid("b7ec40e3-9be7-4201-b2a6-13fb71d41e94")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 1, 1, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            CreatedById = new Guid("d17e004b-2335-4850-8a8a-4597cf73f862"),
                            IsDeleted = false,
                            PermissionId = new Guid("37ec40e3-9be7-4201-b2a6-13fb71d41e94"),
                            RoleId = new Guid("b7ec40e3-9be7-4201-b2a6-13fb71d41e94")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2025, 1, 1, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            CreatedById = new Guid("d17e004b-2335-4850-8a8a-4597cf73f862"),
                            IsDeleted = false,
                            PermissionId = new Guid("47ec40e3-9be7-4201-b2a6-13fb71d41e94"),
                            RoleId = new Guid("b7ec40e3-9be7-4201-b2a6-13fb71d41e94")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2025, 1, 1, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            CreatedById = new Guid("d17e004b-2335-4850-8a8a-4597cf73f862"),
                            IsDeleted = false,
                            PermissionId = new Guid("17ec40e3-9be7-4201-b2a6-13fb71d41e94"),
                            RoleId = new Guid("a7ec40e3-9be7-4201-b2a6-13fb71d41e94")
                        });
                });

            modelBuilder.Entity("LineNex.Domain.Entity.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sensor");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d17e004b-2335-4850-8a8a-4597cf73f862"),
                            CreatedAt = new DateTime(2025, 1, 1, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            CreatedById = new Guid("d17e004b-2335-4850-8a8a-4597cf73f862"),
                            Email = "marcelo.projects.dev@gmail.com",
                            EmailConfirmed = true,
                            IsDeleted = false,
                            Name = "Marcelo Wzorek Filho",
                            Password = "AQAAAAIAAYagAAAAENPeLyJ3XylxuM/AudsOGYLQyT4xYx2JLHr0aJM6G3upSFc2GuspPSfuBVe+bJw0wQ==",
                            RoleId = new Guid("b7ec40e3-9be7-4201-b2a6-13fb71d41e94")
                        });
                });

            modelBuilder.Entity("LineNex.Domain.Entity.UserCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCompany");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.ApplicationToken", b =>
                {
                    b.HasOne("LineNex.Domain.Entity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.DistributionPointMachine", b =>
                {
                    b.HasOne("LineNex.Domain.Entity.DistributionPoint", "DistributionPoint")
                        .WithMany("DistributionPointMachines")
                        .HasForeignKey("DistributionPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LineNex.Domain.Entity.Machine", "Machine")
                        .WithMany("DistributionPointMachines")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DistributionPoint");

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.DistributionPointStock", b =>
                {
                    b.HasOne("LineNex.Domain.Entity.DistributionPoint", null)
                        .WithMany("DistributionPointStocks")
                        .HasForeignKey("DistributionPointId");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.InventoryDistributionPoint", b =>
                {
                    b.HasOne("LineNex.Domain.Entity.DistributionPoint", "DistributionPoint")
                        .WithMany("InventoryDistributionPoints")
                        .HasForeignKey("DistributionPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LineNex.Domain.Entity.Inventory", "Inventory")
                        .WithMany("InventoryDistributionPoints")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DistributionPoint");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.MachineConnection", b =>
                {
                    b.HasOne("LineNex.Domain.Entity.Machine", "Machine")
                        .WithMany("MachineConnections")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.MachineSensor", b =>
                {
                    b.HasOne("LineNex.Domain.Entity.Machine", "Machine")
                        .WithMany("MachineSensors")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LineNex.Domain.Entity.Sensor", "Sensor")
                        .WithMany("MachineSensors")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.MachineSensorData", b =>
                {
                    b.HasOne("LineNex.Domain.Entity.MachineSensor", null)
                        .WithMany("MachineSensorData")
                        .HasForeignKey("MachineSensorId");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.MachineTag", b =>
                {
                    b.HasOne("LineNex.Domain.Entity.Machine", "Machine")
                        .WithMany("MachineTags")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LineNex.Domain.Entity.Tag", "Tag")
                        .WithMany("MachineTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.ProductionLine", b =>
                {
                    b.HasOne("LineNex.Domain.Entity.Company", "Company")
                        .WithMany("ProductionLines")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.ProductionLineMachine", b =>
                {
                    b.HasOne("LineNex.Domain.Entity.Machine", "Machine")
                        .WithMany("ProductionLineMachines")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LineNex.Domain.Entity.ProductionLine", "ProductionLine")
                        .WithMany("ProductionLineMachines")
                        .HasForeignKey("ProductionLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("ProductionLine");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.RolePermission", b =>
                {
                    b.HasOne("LineNex.Domain.Entity.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LineNex.Domain.Entity.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.User", b =>
                {
                    b.HasOne("LineNex.Domain.Entity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.UserCompany", b =>
                {
                    b.HasOne("LineNex.Domain.Entity.Company", "Company")
                        .WithMany("UserCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LineNex.Domain.Entity.User", "User")
                        .WithMany("UserCompanies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.Company", b =>
                {
                    b.Navigation("ProductionLines");

                    b.Navigation("UserCompanies");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.DistributionPoint", b =>
                {
                    b.Navigation("DistributionPointMachines");

                    b.Navigation("DistributionPointStocks");

                    b.Navigation("InventoryDistributionPoints");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.Inventory", b =>
                {
                    b.Navigation("InventoryDistributionPoints");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.Machine", b =>
                {
                    b.Navigation("DistributionPointMachines");

                    b.Navigation("MachineConnections");

                    b.Navigation("MachineSensors");

                    b.Navigation("MachineTags");

                    b.Navigation("ProductionLineMachines");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.MachineSensor", b =>
                {
                    b.Navigation("MachineSensorData");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.ProductionLine", b =>
                {
                    b.Navigation("ProductionLineMachines");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.Sensor", b =>
                {
                    b.Navigation("MachineSensors");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.Tag", b =>
                {
                    b.Navigation("MachineTags");
                });

            modelBuilder.Entity("LineNex.Domain.Entity.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserCompanies");
                });
#pragma warning restore 612, 618
        }
    }
}
