//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LineNex.Specification.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LineNex.Specification.ResxResources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Author ID is required..
        /// </summary>
        internal static string AuthorIdRequiredValidation
        {
            get
            {
                return ResourceManager.GetString("AuthorIdRequiredValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Code must not exceed the maximum allowed length..
        /// </summary>
        internal static string CodeMaximumLengthValidation
        {
            get
            {
                return ResourceManager.GetString("CodeMaximumLengthValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Code must meet the minimum length requirement..
        /// </summary>
        internal static string CodeMinimumLengthValidation
        {
            get
            {
                return ResourceManager.GetString("CodeMinimumLengthValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Code is required..
        /// </summary>
        internal static string CodeRequiredValidation
        {
            get
            {
                return ResourceManager.GetString("CodeRequiredValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Color must be in valid hexadecimal format (e.g., #e2e2e2)..
        /// </summary>
        internal static string ColorHexFormatValidation
        {
            get
            {
                return ResourceManager.GetString("ColorHexFormatValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Color is required..
        /// </summary>
        internal static string ColorRequiredValidation
        {
            get
            {
                return ResourceManager.GetString("ColorRequiredValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Company ID is required..
        /// </summary>
        internal static string CompanyIdRequiredValidation
        {
            get
            {
                return ResourceManager.GetString("CompanyIdRequiredValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connected Machine ID is required..
        /// </summary>
        internal static string ConnectedMachineIdRequiredValidation
        {
            get
            {
                return ResourceManager.GetString("ConnectedMachineIdRequiredValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description must not exceed the maximum allowed length..
        /// </summary>
        internal static string DescriptionMaximumLengthValidation
        {
            get
            {
                return ResourceManager.GetString("DescriptionMaximumLengthValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Distribution Point ID is required..
        /// </summary>
        internal static string DistributionPointIdRequiredValidation
        {
            get
            {
                return ResourceManager.GetString("DistributionPointIdRequiredValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email format is invalid..
        /// </summary>
        internal static string EmailInvalidFormatValidation
        {
            get
            {
                return ResourceManager.GetString("EmailInvalidFormatValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email must not exceed the maximum allowed length..
        /// </summary>
        internal static string EmailMaximumLengthValidation
        {
            get
            {
                return ResourceManager.GetString("EmailMaximumLengthValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        internal static string EmailRequiredValidation
        {
            get
            {
                return ResourceManager.GetString("EmailRequiredValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Inventory ID is required..
        /// </summary>
        internal static string InventoryIdRequiredValidation
        {
            get
            {
                return ResourceManager.GetString("InventoryIdRequiredValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Machine ID is required..
        /// </summary>
        internal static string MachineIdRequiredValidation
        {
            get
            {
                return ResourceManager.GetString("MachineIdRequiredValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Machine ID for the machine sensor is required..
        /// </summary>
        internal static string MachineSensorMachineIdRequiredValidation
        {
            get
            {
                return ResourceManager.GetString("MachineSensorMachineIdRequiredValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sensor ID for the machine sensor is required..
        /// </summary>
        internal static string MachineSensorSensorIdRequiredValidation
        {
            get
            {
                return ResourceManager.GetString("MachineSensorSensorIdRequiredValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name must not exceed the maximum allowed length..
        /// </summary>
        internal static string NameMaximumLengthValidation
        {
            get
            {
                return ResourceManager.GetString("NameMaximumLengthValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        internal static string NameRequiredValidation
        {
            get
            {
                return ResourceManager.GetString("NameRequiredValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Permission ID is required..
        /// </summary>
        internal static string PermissionIdRequiredValidation
        {
            get
            {
                return ResourceManager.GetString("PermissionIdRequiredValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Production Line ID is required..
        /// </summary>
        internal static string ProductionLineIdRequiredValidation
        {
            get
            {
                return ResourceManager.GetString("ProductionLineIdRequiredValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quantity must be within the allowed range..
        /// </summary>
        internal static string QuantityRangeValidation
        {
            get
            {
                return ResourceManager.GetString("QuantityRangeValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quantity is required..
        /// </summary>
        internal static string QuantityRequiredValidation
        {
            get
            {
                return ResourceManager.GetString("QuantityRequiredValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Role ID is required..
        /// </summary>
        internal static string RoleIdRequiredValidation
        {
            get
            {
                return ResourceManager.GetString("RoleIdRequiredValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sensor ID is required..
        /// </summary>
        internal static string SensorIdRequiredValidation
        {
            get
            {
                return ResourceManager.GetString("SensorIdRequiredValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tag ID is required..
        /// </summary>
        internal static string TagIdRequiredValidation
        {
            get
            {
                return ResourceManager.GetString("TagIdRequiredValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User ID is required..
        /// </summary>
        internal static string UserIdRequiredValidation
        {
            get
            {
                return ResourceManager.GetString("UserIdRequiredValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Value exceeds the maximum allowed length..
        /// </summary>
        internal static string ValueMaximumLengthValidation
        {
            get
            {
                return ResourceManager.GetString("ValueMaximumLengthValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Value is required..
        /// </summary>
        internal static string ValueRequiredValidation
        {
            get
            {
                return ResourceManager.GetString("ValueRequiredValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        internal static string PasswordRequiredValidation
        {
            get
            {
                return ResourceManager.GetString("PasswordRequiredValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password must not exceed the maximum allowed length.
        /// </summary>
        internal static string PasswordMaximumLengthValidation
        {
            get
            {
                return ResourceManager.GetString("PasswordMaximumLengthValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh token is required.
        /// </summary>
        internal static string RefreshTokenRequiredValidation
        {
            get
            {
                return ResourceManager.GetString("RefreshTokenRequiredValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Activation token is required.
        /// </summary>
        internal static string ActivateTokenRequiredValidation
        {
            get
            {
                return ResourceManager.GetString("ActivateTokenRequiredValidation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Forgot Password token is required.
        /// </summary>
        internal static string ForgotPasswordTokenRequiredValidation
        {
            get
            {
                return ResourceManager.GetString("ForgotPasswordTokenRequiredValidation", resourceCulture);
            }
        }
    }
}
